### ISSUE TITLE
Missing dist/main.js

### ISSUE THREAD

**Issue by SirDarquan** [fast-facts/ng-update#896]
Hi,

I was wondering if you could fix this problem I have. When I set it up, like the other projects I have, I get this error saying Error: File not found: '/home/runner/work/_actions/fast-facts/ng-update/master/dist/main.js'. No idea what this was from. Hopefully you can fix it for me. 

Thanks.

**Comment by fast-facts** [comment]
Give it another try. I just rebuilt it and tested it on my another repo.

**Comment by SirDarquan** [comment]
Nope. It's now giving this insead: Error: The process '/usr/local/bin/npm' failed with exit code 1

**Comment by fast-facts** [comment]
Try once more. I just rebuilt everything and it worked on one of my other repos.

If it doesn't work for you, post your workflow file and log.

**Comment by SirDarquan** [comment]
I'm sorry. I didn't get to work on it more. I got the same old error: Error: The process '/usr/local/bin/npm' failed with exit code 1 but this time it happened during while trying to "ng update" the code.

**Comment by SirDarquan** [comment]
[logs_29565126404.zip](https://github.com/user-attachments/files/17365167/logs_29565126404.zip)

I think I know why it fails. Tell me it's true or not
